const genres = [
  "Acid rock",
  "Alternative metal",
  "Alternative rock",
  "Anarcho punk",
  "Art punk",
  "Art rock",
  "Avant-garde metal",
  "Beat music",
  "Black metal",
  "Blues rock",
  "Canterbury scene",
  "Celtic metal",
  "Celtic punk",
  "Chinese rock",
  "Christian metal",
  "Christian punk",
  "Christian rock",
  "Cowpunk",
  "Crossover thrash",
  "Crust punk",
  "Crustgrind",
  "D-beat",
  "Dark cabaret",
  "Death 'n' roll",
  "Death metal",
  "Death-doom",
  "Deathcore",
  "Deathrock",
  "Desert rock",
  "Digital hardcore",
  "Djent",
  "Doom metal",
  "Dream Pop",
  "Drone metal",
  "Dunedin Sound",
  "Electronic rock",
  "Electronicore",
  "Emo",
  "Experimental rock",
  "Folk metal",
  "Folk punk",
  "Folk rock",
  "Freakbeat",
  "Funk metal",
  "Garage punk",
  "Garage rock",
  "Glam metal",
  "Glam rock",
  "Goregrind",
  "Gothic metal",
  "Gothic rock",
  "Grindcore",
  "Groove metal",
  "Grunge",
  "Gypsy punk",
  "Hard rock",
  "Hardcore punk",
  "Heavy metal",
  "Horror punk",
  "Indie rock",
  "Industrial metal",
  "Industrial rock",
  "Jazz rock",
  "Krautrock",
  "Latin metal",
  "Math rock",
  "Mathcore",
  "Medieval metal",
  "Melodic death metal",
  "Melodic metalcore",
  "Metalcore",
  "Nagoya kei",
  "Neo-psychedelia",
  "Neoclassical metal",
  "Neue Deutsche Härte",
  "New prog",
  "New wave",
  "No wave",
  "Noise rock",
  "Noisegrind",
  "Nu metal",
  "Pagan metal",
  "Paisley Underground",
  "Pop punk",
  "Pop rock",
  "Post-grunge",
  "Post-hardcore",
  "Post-metal",
  "Post-punk",
  "Post-punk revival",
  "Post-rock",
  "Power metal",
  "Powerviolence",
  "Progressive metal",
  "Progressive rock",
  "Psychedelic rock",
  "Psychobilly",
  "Punk rock",
  "Raga rock",
  "Rap metal",
  "Rap rock",
  "Rapcore",
  "Riot grrrl",
  "Rock and roll",
  "Rock in Opposition",
  "Sadcore",
  "Screamo",
  "Shoegaze",
  "Ska punk",
  "Skate punk",
  "Slowcore",
  "Sludge metal",
  "Soft rock",
  "Southern rock",
  "Space rock",
  "Speed metal",
  "Stoner rock",
  "Street punk",
  "Sufi rock",
  "Surf rock",
  "Symphonic black metal",
  "Symphonic metal",
  "Technical death metal",
  "Thrash metal",
  "Thrashcore",
  "Turkish rock",
  "Turkish metal",
  "Unblack metal",
  "Viking metal",
  "Visual kei",
  "War metal",
  "World fusion",
  "Worldbeat",
];

module.exports = genres;
